
import json
import re

# I will paste the mockMembers array content here manually in the script
# But since I can't interactively paste, I'll put the data in the script.

mock_members_data = """
[
  {
    "id": 1,
    "name": "Akhilesh Joshi",
    "role": "Chairperson",
    "branch": "Computer Science",
    "year": 4,
    "email": "akhilesh.joshi@kle.edu",
    "skills": ["Leadership", "React", "Node.js", "Management"],
    "joinDate": "2022-08-15",
    "bio": "Leading ArcStack with passion for innovation and technology",
    "image": "/test-profile.svg"
  },
  {
    "id": 2,
    "name": "Anushka Singh",
    "role": "Vice Chairperson",
    "branch": "Computer Science",
    "year": 3,
    "email": "anushka.singh@kle.edu",
    "skills": ["Management", "Python", "Web Development"],
    "joinDate": "2023-08-15",
    "bio": "Supporting club operations and driving technical excellence",
    "image": "/test-profile.svg"
  },
  {
    "id": 3,
    "name": "PRATIK KESARKAR",
    "role": "General Secretary",
    "branch": "CSAI",
    "year": 4,
    "email": "pratikkesarkar04@gmail.com",
    "skills": ["Java", "MERN Stack", "DSA"],
    "joinDate": "2022-08-15",
    "bio": "Aspiring Computer Science student focused on AI and Full Stack Development, passionate about building innovative solutions that drive growth.",
    "image": "/images/members/pratik-kesarkar.jpg",
    "linkedin": "https://www.linkedin.com/in/pratik-kesarkar-2a65242a2",
    "github": "https://github.com/PRATIK-KESARKAR",
    "instagram": "https://www.instagram.com/pratik__kesarkar/"
  },
  {
    "id": 4,
    "name": "Shreyas Savant",
    "role": "Deputy General Secretary",
    "branch": "Computer Science",
    "year": 3,
    "email": "shreyas.savant@kle.edu",
    "skills": ["Coordination", "React", "Backend"],
    "joinDate": "2023-08-15",
    "bio": "Assisting in club management and technical initiatives",
    "image": "/test-profile.svg"
  },
  {
    "id": 5,
    "name": "Samarth Kattimani",
    "role": "Treasurer",
    "branch": "Computer Science",
    "year": 4,
    "email": "samarth.kattimani@kle.edu",
    "skills": ["Finance", "Management", "Web Development"],
    "joinDate": "2022-08-15",
    "bio": "Managing club finances and budgeting",
    "image": "/test-profile.svg"
  },
  {
    "id": 6,
    "name": "Aniket Patil",
    "role": "Treasurer",
    "branch": "Computer Science",
    "year": 3,
    "email": "aniket.patil@kle.edu",
    "skills": ["Finance", "Accounting", "Python"],
    "joinDate": "2023-08-15",
    "bio": "Co-managing financial operations",
    "image": "/test-profile.svg"
  },
  {
    "id": 7,
    "name": "Harshit Baliyan",
    "role": "Lead (Development Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "harshit.baliyan@kle.edu",
    "skills": ["Full Stack", "React", "Node.js", "MongoDB"],
    "joinDate": "2023-08-15",
    "bio": "Leading development team and building scalable applications",
    "image": "/test-profile.svg"
  },
  {
    "id": 8,
    "name": "Neil Rego",
    "role": "Lead (AI Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "neil.rego@kle.edu",
    "skills": ["Machine Learning", "Python", "TensorFlow", "AI"],
    "joinDate": "2023-08-15",
    "bio": "Leading AI initiatives and ML projects",
    "image": "/test-profile.svg"
  },
  {
    "id": 9,
    "name": "Rahul Kulkarni",
    "role": "Co-Lead (AI Team)",
    "branch": "CSAI",
    "year": 4,
    "email": "Rahulkulkarni2944@gmail.com",
    "skills": ["Deep Learning", "Python", "Data Science", "Machine Learning"],
    "joinDate": "2022-08-15",
    "bio": "7th semester, CS-AI",
    "image": "/images/members/rahul-kulkarni.jpeg",
    "linkedin": "https://www.linkedin.com/in/rahul-kulkarni-19890827a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    "instagram": "https://www.instagram.com/rahul_kulkarni.xvi?igsh=MW95emd6MmNsdGdibA%3D%3D&utm_source=qr"
  },
  {
    "id": 10,
    "name": "Aastha Mishra",
    "role": "Lead (Emerging Tech)",
    "branch": "CSE",
    "year": 3,
    "email": "aastha1.official@gmail.com",
    "skills": ["Java", "Cloud Computing", "Content Creation", "Public Relations"],
    "joinDate": "2023-08-15",
    "bio": "I am Aastha, a 3rd year undergraduate at KLE Technological University (KLETU) pursuing Computer Science and Engineering. I am an inquisitive explorer and learner in the realms of technology, innovation, and creativity.",
    "image": "/images/members/aastha-mishra.jpg",
    "linkedin": "https://www.linkedin.com/in/aastha-mishra-99ba71356?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
  },
  {
    "id": 11,
    "name": "Prakhar Shresth",
    "role": "Co-Lead (Emerging Tech)",
    "branch": "CSE",
    "year": 3,
    "email": "prakhar.shresth01@gmail.com",
    "skills": ["Java", "Machine Learning", "Data Science", "DSA", "Algorithms", "Design", "Blockchain"],
    "joinDate": "2023-08-15",
    "bio": "My name is Prakhar Shrestha, and I am a Computer Science Engineering student pursuing my B.Tech with a strong interest in technology and its evolving landscape. I have knowledge in Web Development, Machine Learning, and Java, and I am currently exploring ways to strengthen my skills further. I plan to learn App Development and Generative AI, and I am also considering areas like Blockchain and Cybersecurity in the future. I see myself as a continuous learner who enjoys building new skills and adapting to emerging technologies. Outside academics, I play football and basketball, and I also enjoy playing the guitar, which keeps me creative and balanced.",
    "image": "/images/members/prakhar-shrestha.jpg",
    "linkedin": "https://www.linkedin.com/in/prakhar-shrestha-b9527027a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "github": "https://github.com/prakharshrestha",
    "instagram": "https://www.instagram.com/prakhar.shresth_._?igsh=cHBrMXBtN2tqN2Vv"
  },
  {
    "id": 12,
    "name": "Ankit Raj",
    "role": "Lead (Competition Management)",
    "branch": "CSE",
    "year": 3,
    "email": "ankitrajj23@gmail.com",
    "skills": ["C++", "WebDev", "ML/DL", "Machine learning", "Data analysis"],
    "joinDate": "2023-08-15",
    "bio": "Pursuing B.Tech in CSE. Proficient in Machine learning, data analysis and software development.",
    "image": "/images/members/ankit-raj.jpg",
    "linkedin": "https://www.linkedin.com/in/ankit-raj-96237b369"
  },
  {
    "id": 13,
    "name": "Bhumika N",
    "role": "Lead (PR Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "bhumika.n@kle.edu",
    "skills": ["Public Relations", "Communication", "Marketing"],
    "joinDate": "2023-08-15",
    "bio": "Managing public relations and outreach",
    "image": "/test-profile.svg"
  },
  {
    "id": 14,
    "name": "Aryan Patil",
    "role": "Co-Lead (PR Team)",
    "branch": "Computer Science",
    "year": 2,
    "email": "aryan.patil@kle.edu",
    "skills": ["Social Media", "Content Creation", "Marketing"],
    "joinDate": "2024-08-15",
    "bio": "Supporting PR activities and social media management",
    "image": "/test-profile.svg"
  },
  {
    "id": 15,
    "name": "Adarsh Kakatkar",
    "role": "Lead (Programming Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "adarsh.kakatkar@kle.edu",
    "skills": ["C++", "Python", "Algorithms", "Problem Solving"],
    "joinDate": "2023-08-15",
    "bio": "Leading programming team and competitive coding",
    "image": "/test-profile.svg"
  },
  {
    "id": 16,
    "name": "Vaibhav Deopa",
    "role": "Co-Lead (Programming Team)",
    "branch": "CSAI",
    "year": 3,
    "email": "udaydeopa2023@gmail.com",
    "skills": ["Competitive Programming", "DSA", "Node.js", "Python", "C++", "Java"],
    "joinDate": "2023-08-15",
    "bio": "You know it not the same as it was",
    "image": "/images/members/vaibhav-deopa.jpg",
    "linkedin": "https://www.linkedin.com/in/vaibhavdeopa/",
    "github": "https://github.com/VaibhavDeopa",
    "instagram": "https://www.instagram.com/vaibhav_deopa/"
  },
  {
    "id": 17,
    "name": "Anusha Rokhade",
    "role": "Lead (Media & Design)",
    "branch": "CSE",
    "year": 3,
    "email": "rokhadeanusha@gmail.com",
    "skills": ["design", "editing", "Java", "machine learning"],
    "joinDate": "2023-08-15",
    "bio": "..",
    "image": "/images/members/anusha-rokhade.jpg",
    "linkedin": "https://www.linkedin.com/in/anusha-rokhade-b41b72389"
  },
  {
    "id": 18,
    "name": "Jaydeep Nadkarni",
    "role": "Member (Development Team)",
    "branch": "CSE",
    "year": 2,
    "email": "jaydeepnadkarni123@gmail.com",
    "skills": ["React", "Node.js", "UI/UX", "Python"],
    "joinDate": "2024-08-15",
    "bio": "Web developer",
    "image": "/images/members/jaydeep-nadkarni.jpg",
    "linkedin": "https://www.linkedin.com/in/jaydeep-nadkarni",
    "github": "https://github.com/Jaydeep-Nadkarni",
    "instagram": "https://www.instagram.com/jaydeep_nadkarni/"
  },
  {
    "id": 19,
    "name": "Shivakumar A Sindolli",
    "role": "Member (Development Team)",
    "branch": "CSE",
    "year": 2,
    "email": "shivakumarshindolli@gmail.com",
    "skills": ["React", "node.js", "DSA"],
    "joinDate": "2024-08-15",
    "bio": "I am a curious learner who enjoys coding and exploring new technologies. I am interested in web technology, AI, DSA. I enjoy working in teams and learning from others. I joined the Coding Club to grow, collaborate, and become a better developer.",
    "image": "/images/members/shivakumar-sindolli.jpg",
    "linkedin": "https://www.linkedin.com/in/shivakumar-sindolli-7b4b69394/",
    "github": "https://github.com/ShivakumarSindolli",
    "instagram": "https://www.instagram.com/shivakumar_sindolli/?next=%2F"
  },
  {
    "id": 20,
    "name": "Samiksha Yadav",
    "role": "Member (Development Team)",
    "branch": "CSE",
    "year": 2,
    "email": "02fe24bcs051@kletech.ac.in",
    "skills": ["React", "Node.js", "figma"],
    "joinDate": "2024-08-15",
    "bio": "I am a Computer Science student actively learning both web development and cybersecurity. I enjoy building projects, exploring new technologies, and continuously improving my technical skills.",
    "image": "/images/members/samiksha-yadav.jpeg",
    "linkedin": "https://www.linkedin.com/in/samiksha-yadav-536315308",
    "github": "github.com/samikshayadav-ux",
    "instagram": "https://instagram.com/samiksha872"
  },
  {
    "id": 21,
    "name": "Kartik Hirenarti",
    "role": "Member (Development Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "kartik.hirenarti@kle.edu",
    "skills": ["HTML", "CSS", "JavaScript"],
    "joinDate": "2024-08-15",
    "bio": "Learning web development",
    "image": "/test-profile.svg"
  },
  {
    "id": 22,
    "name": "Divya Gour",
    "role": "Member (Development Team)",
    "branch": "CSE",
    "year": 1,
    "email": "divyagour0935@gmail.com",
    "skills": ["Java", "C++", "C", "Web dev"],
    "joinDate": "2024-08-15",
    "bio": "I'm Divya Gour, a Computer Science Engineering undergraduate at KLE Technological University. I have hands-on experience in C and C++ and a solid understanding of the basics of web development and I'm currently expanding my knowledge in that area, along with learning Java . I'm passionate about technology and personal growth , eager to apply my skills to real-world projects.",
    "image": "/images/members/divya-gour.jpg",
    "linkedin": "www.linkedin.com/in/divya-gour",
    "github": "https://github.com/Divya-Gour",
    "instagram": "https://www.instagram.com/divyagour._?igsh=eTJmZGIxNm9nZ3I0"
  },
  {
    "id": 23,
    "name": "Abhishek Manoli",
    "role": "Member (Development Team)",
    "branch": "CSE",
    "year": 1,
    "email": "abhishekmanoli2007@gmail.com",
    "skills": ["DSA", "C++", "Social Media Marketing", "Content Creation", "PR", "Editing"],
    "joinDate": "2024-08-15",
    "bio": "I am a first-year Computer Science and Engineering student with a strong interest in software development, artificial intelligence, and cybersecurity. I believe in learning by doing, and I enjoy experimenting, building projects, and applying knowledge to solve real-world problems. I recently participated in the Smart India Hackathon (SIH 2025), which helped me develop teamwork, brainstorming, and problem-solving skills. I am also an active member of my college’s HR Club and am known for being a motivated team player with natural leadership qualities. Outside academics, I enjoy playing football, gaming, and exploring nature through trekking. I aim to grow my skills and pursue opportunities that help me become an engineer who turns ideas into meaningful solutions.",
    "image": "/images/members/abhishek-manoli.jpg",
    "linkedin": "www.linkedin.com/in/abhishekmanoli",
    "github": "https://github.com/abhishekmanoli",
    "instagram": "https://www.instagram.com/abhishek_manoli"
  },
  {
    "id": 24,
    "name": "Harshit Jakati",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "harshit.jakati@kle.edu",
    "skills": ["Machine Learning", "Python", "TensorFlow"],
    "joinDate": "2023-08-15",
    "bio": "AI and ML enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 25,
    "name": "Chandrakanth D Ujjanagoudra",
    "role": "Member (AI Team)",
    "branch": "CSAI",
    "year": 2,
    "email": "02fe24bci049@kletech.ac.in",
    "skills": ["Python", "ML"],
    "joinDate": "2024-08-15",
    "bio": "Ai Enthusiast",
    "image": "/images/members/chandrakanth-ujjanagoudra.jpg",
    "linkedin": "https://www.linkedin.com/in/chandrakanth-d-u-6291b0327?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
  },
  {
    "id": 26,
    "name": "Arpita Malalikar",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 2,
    "email": "arpita.malalikar@kle.edu",
    "skills": ["Machine Learning", "Data Science", "Python"],
    "joinDate": "2024-08-15",
    "bio": "Data science and ML practitioner",
    "image": "/test-profile.svg"
  },
  {
    "id": 27,
    "name": "Vaishnavi Modekar",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 2,
    "email": "vaishnavi.modekar@kle.edu",
    "skills": ["AI", "Python", "Machine Learning"],
    "joinDate": "2024-08-15",
    "bio": "AI research enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 28,
    "name": "Chinmayi T",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "chinmayi.t@kle.edu",
    "skills": ["Python", "Machine Learning"],
    "joinDate": "2024-08-15",
    "bio": "Learning AI and ML",
    "image": "/test-profile.svg"
  },
  {
    "id": 29,
    "name": "Shreya Kalaj",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "shreya.kalaj@kle.edu",
    "skills": ["Python", "Data Analysis"],
    "joinDate": "2024-08-15",
    "bio": "Data analysis and AI learner",
    "image": "/test-profile.svg"
  },
  {
    "id": 30,
    "name": "Varshini Kulkarni",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "varshini.kulkarni@kle.edu",
    "skills": ["Python", "Machine Learning"],
    "joinDate": "2024-08-15",
    "bio": "Aspiring ML engineer",
    "image": "/test-profile.svg"
  },
  {
    "id": 31,
    "name": "Varsha B",
    "role": "Member (AI Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "varsha.b@kle.edu",
    "skills": ["Python", "AI"],
    "joinDate": "2024-08-15",
    "bio": "AI enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 32,
    "name": "Manmohan Havanur",
    "role": "Member (Emerging Tech)",
    "branch": "Computer Science",
    "year": 1,
    "email": "manmohan.havanur@kle.edu",
    "skills": ["Blockchain", "Web3"],
    "joinDate": "2024-08-15",
    "bio": "Blockchain technology explorer",
    "image": "/test-profile.svg"
  },
  {
    "id": 33,
    "name": "Rudra Kulkarni",
    "role": "Member (Emerging Tech)",
    "branch": "Computer Science",
    "year": 1,
    "email": "rudra.kulkarni@kle.edu",
    "skills": ["IoT", "Cloud Computing"],
    "joinDate": "2024-08-15",
    "bio": "IoT and cloud enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 34,
    "name": "Siddu Patil",
    "role": "Member (Emerging Tech)",
    "branch": "ECE",
    "year": 1,
    "email": "patilsiddu266@gmail.com",
    "skills": ["IoT", "Arduino IDE", "ESP32"],
    "joinDate": "2024-08-15",
    "bio": "ECE freshman passionate in learning programming, Arduino IDE, and IoT development. Skilled with ESP32, relays, servos, steppers, and DC motors.",
    "image": "/images/members/siddu-patil.jpg",
    "linkedin": "https://www.linkedin.com/in/siddu-patil-27ab46395",
    "github": "https://github.com/patilsiddu",
    "instagram": "https://www.instagram.com/_siddangouda.patil_?igsh=MTRweXV1dzBkOXFkZw%3D%3D&utm_source=qr"
  },
  {
    "id": 35,
    "name": "Shivaleela",
    "role": "Member (Emerging Tech)",
    "branch": "Computer Science",
    "year": 2,
    "email": "shivaleela@kle.edu",
    "skills": ["Cloud", "DevOps"],
    "joinDate": "2024-08-15",
    "bio": "Cloud computing learner",
    "image": "/test-profile.svg"
  },
  {
    "id": 36,
    "name": "Namrata Basaragi",
    "role": "Member (Emerging Tech)",
    "branch": "Computer Science",
    "year": 1,
    "email": "namrata@kle.edu",
    "skills": ["Blockchain", "Web3"],
    "joinDate": "2024-08-15",
    "bio": "Web3 technology enthusiast",
    "image": "/images/members/namrata.jpg"
  },
  {
    "id": 37,
    "name": "Aditya Hiremath",
    "role": "Member (Emerging Tech)",
    "branch": "CSE",
    "year": 1,
    "email": "adityahiremath1024@gmail.com",
    "skills": ["Frontend", "C"],
    "joinDate": "2024-08-15",
    "bio": "Name :Aditya M Hiremath Age :19 1st year Cse Class:C",
    "image": "/images/members/aditya-hiremath.jpg",
    "linkedin": "http://www.linkedin.com/in/aditya-hiremath-2a95012a1",
    "github": "https://github.com/adityahiremath449",
    "instagram": "https://www.instagram.com/aditya_____2416?igsh=NzB5cDBld2NodGhk"
  },
  {
    "id": 38,
    "name": "Daivik Naik",
    "role": "Member (Competition Management)",
    "branch": "CSE",
    "year": 3,
    "email": "daiviknaik23@gmail.com",
    "skills": ["Python", "C", "C++", "Machine learning", "Deep Learning", "Cloud Computing", "Java", "Computer Vision"],
    "joinDate": "2023-08-15",
    "bio": "I’m a third-year Computer Science Engineering student with a strong interest in software development and intelligent technologies. I enjoy working with Python, C, C++, and Java, and I actively explore Machine Learning, Deep Learning, Computer Vision, and Cloud Computing to build practical, real-world solutions and keep improving my skills every day.",
    "image": "/images/members/daivik-naik.png",
    "linkedin": "www.linkedin.com/in/daiviknaik",
    "github": "https://github.com/daiviknaik23",
    "instagram": "https://www.instagram.com/daivik.p.n_081/"
  },
  {
    "id": 39,
    "name": "Srushti Payannawar",
    "role": "Member (Competition Management)",
    "branch": "Computer Science",
    "year": 1,
    "email": "srushti.payannawar@kle.edu",
    "skills": ["Problem Solving", "Algorithms"],
    "joinDate": "2024-08-15",
    "bio": "Problem solving enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 40,
    "name": "Sumedha Upadhye",
    "role": "Member (Competition Management)",
    "branch": "ECE",
    "year": 1,
    "email": "upadhyesumedha395@gmail.com",
    "skills": ["IoT", "Public Relations", "Arduino IDE"],
    "joinDate": "2024-08-15",
    "bio": "ECE freshman learning programming, Arduino IDE, and IoT development. Skilled with ESP32, relays, servos, steppers, and DC motors.",
    "image": "/images/members/sumedha-upadhye.jpg",
    "linkedin": "https://www.linkedin.com/in/sumedha-upadhye-444172385?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "github": "https://github.com/usumedha8-afk",
    "instagram": "https://www.instagram.com/sumedha___91?igsh=MTM1b2U0M3JhYzcyZQ=="
  },
  {
    "id": 41,
    "name": "Tanisha",
    "role": "Member (Competition Management)",
    "branch": "Computer Science",
    "year": 3,
    "email": "tanisha@kle.edu",
    "skills": ["Algorithms", "Problem Solving"],
    "joinDate": "2023-08-15",
    "bio": "Algorithm design enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 42,
    "name": "Vaibhav Lakkashetti",
    "role": "Member (Competition Management)",
    "branch": "CSE",
    "year": 1,
    "email": "vaibhavrlakkashetti@gmail.com",
    "skills": ["Python", "DSA and algorithms", "Machine learning"],
    "joinDate": "2024-08-15",
    "bio": "I have done my schooling in Dnyan Prabodhan Mandir ICSE board school and my PUC State board in KLE Independent college.",
    "image": "/images/members/vaibhav-lakkashetti.jpeg",
    "linkedin": "https://www.linkedin.com/in/vaibhav-lakkashetti-26116338a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    "github": "https://github.com/vaibhavrlakkashetti-08",
    "instagram": "https://www.instagram.com/vaibhavshetty_82?igsh=eWtjOTh0bzVyOTk4&utm_source=qr"
  },
  {
    "id": 43,
    "name": "Shreya Pai",
    "role": "Member (Competition Management)",
    "branch": "Computer Science",
    "year": 2,
    "email": "shreya.pai@kle.edu",
    "skills": ["Problem Solving", "Algorithms"],
    "joinDate": "2024-08-15",
    "bio": "Competitive coding enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 44,
    "name": "Sanaha Mugurkhan",
    "role": "Member (Competition Management)",
    "branch": "Computer Science",
    "year": 1,
    "email": "sanaha.mugurkhan@kle.edu",
    "skills": ["Algorithms", "DSA"],
    "joinDate": "2024-08-15",
    "bio": "Algorithm enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 45,
    "name": "Pavitra H",
    "role": "Member (PR Team)",
    "branch": "Computer Science",
    "year": 2,
    "email": "pavitra.h@kle.edu",
    "skills": ["Communication", "Social Media", "Marketing"],
    "joinDate": "2024-08-15",
    "bio": "Social media and PR specialist",
    "image": "/test-profile.svg"
  },
  {
    "id": 46,
    "name": "Sneha Hundekar",
    "role": "Member (PR Team)",
    "branch": "Computer Science",
    "year": 2,
    "email": "sneha.hundekar@kle.edu",
    "skills": ["Public Relations", "Content Creation"],
    "joinDate": "2024-08-15",
    "bio": "Content creator and PR enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 47,
    "name": "Saamiya Shaikh",
    "role": "Member (PR Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "saumya.shaikh@kle.edu",
    "skills": ["Communication", "Marketing"],
    "joinDate": "2024-08-15",
    "bio": "Marketing and communication learner",
    "image": "/test-profile.svg"
  },
  {
    "id": 48,
    "name": "Mallikarjunagouda Patil",
    "role": "Member (PR Team)",
    "branch": "CSAI",
    "year": 1,
    "email": "mallikarjunagoudapatil864@gmail.com",
    "skills": ["C++", "C", "Art", "Team Management"],
    "joinDate": "2024-08-15",
    "bio": "I am Mallikarjungouda Patil, currently pursuing Computer Science (AI) at KLE Sheshgiri College, Belgaum. I have a keen interest in coding, anime, and traveling, and I aspire to become a VFX and Animation Artist. I completed my Pre-University education (11th and 12th) at RLS PU College of Science, Belgaum. I completed my 1st to 10th education at St. Xavier’s High School, where I served as the Speaker of the School Cabinet in 10th grade.",
    "image": "/images/members/mallikarjunagouda-patil.png",
    "linkedin": "https://www.linkedin.com/in/mallikarjungouda-patil-889174398?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "github": "https://github.com/Mallikarjungouda-28"
  },
  {
    "id": 49,
    "name": "Pranjali Mutagekar",
    "role": "Member (PR Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "pranjali.muragakar@kle.edu",
    "skills": ["Marketing", "Communication"],
    "joinDate": "2023-08-15",
    "bio": "Marketing specialist",
    "image": "/test-profile.svg"
  },
  {
    "id": 50,
    "name": "Spandana B",
    "role": "Member (PR Team)",
    "branch": "Computer Science",
    "year": 2,
    "email": "spandana.b@kle.edu",
    "skills": ["Content Creation", "Social Media"],
    "joinDate": "2024-08-15",
    "bio": "Content and social media specialist",
    "image": "/test-profile.svg"
  },
  {
    "id": 51,
    "name": "Lomesh Kumar",
    "role": "Member (Programming Team)",
    "branch": "CSAI",
    "year": 3,
    "email": "ansukujangde.13@gmail.com",
    "skills": ["C++", "DSA", "Web Development", "Video Editing", "Public Speaking", "Content Creation"],
    "joinDate": "2023-08-15",
    "bio": "Solving problems, enjoying the process.",
    "image": "/images/members/lomesh-kumar.jpg",
    "linkedin": "www.linkedin.com/in/lomesh-jangde-8572a7311",
    "github": "https://github.com/LomeshKuJangde",
    "instagram": "https://www.instagram.com/lomesh_jangde_/"
  },
  {
    "id": 52,
    "name": "Arun Kumar Mokashi",
    "role": "Member (Programming Team)",
    "branch": "CSAI",
    "year": 3,
    "email": "arunmokashi2105@gmail.com",
    "skills": ["Java", "python", "Machine Learning", "Deep Learning", "Data Science", "Algorithms", "DSA"],
    "joinDate": "2023-08-15",
    "bio": "Hello, everyone! I'm Arun Mokashi, a third-year student. Currently, I'm sharpening my skills in two directions: getting better at solving algorithm problems (LeetCode is my daily hobby) and learning to write cleaner, more efficient code every day! As a third-year AI student, I’m fascinated by how machines can be trained to think in their own way, and I'm also working on improving my coding skills by contributing to open-source projects. My technical toolkit includes Java and Python, along with a growing focus on Machine Learning, Deep Learning, and DSA.",
    "image": "/images/members/arun-kumar.png",
    "linkedin": "https://www.linkedin.com/in/arun-kumar-mokashi-4062ba2b2/",
    "github": "https://github.com/arunkumar-ak21"
  },
  {
    "id": 53,
    "name": "Samarth Narvekar",
    "role": "Member (Programming Team)",
    "branch": "Computer Science",
    "year": 3,
    "email": "samarth.narvekar@kle.edu",
    "skills": ["C++", "Algorithms", "Competitive Programming"],
    "joinDate": "2023-08-15",
    "bio": "Algorithm design specialist",
    "image": "/test-profile.svg"
  },
  {
    "id": 54,
    "name": "Darshan Kittur",
    "role": "Member (Programming Team)",
    "branch": "CSE",
    "year": 2,
    "email": "darshankittur79@gmail.com",
    "skills": ["C", "cpp", "python"],
    "joinDate": "2024-08-15",
    "bio": "I am a passionate learner with a strong interest in technology, coding, and problem-solving.",
    "image": "/images/members/darshan-kittur.jpg",
    "linkedin": "https://www.linkedin.com/in/darshan-kittur-65532a326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "github": "https://github.com/darshankittur79",
    "instagram": "https://www.instagram.com/darshankittur_79?igsh=MTZsc3ZkY3hjZHQxbQ=="
  },
  {
    "id": 55,
    "name": "Namrata Suryavanshi",
    "role": "Member (Programming Team)",
    "branch": "CSE",
    "year": 2,
    "email": "namratasuryavanshi422@gmail.com",
    "skills": ["C++", "Competitive programming", "Algorithm", "DSA"],
    "joinDate": "2024-08-15",
    "bio": "A focused and enthusiastic learner who believes in continuous improvement. I have a keen interest in computer science, coding, and developing real-world solutions.",
    "image": "/images/members/namrata-suryavanshi.png",
    "linkedin": "https://www.linkedin.com/in/namrata-suryavanshi-848024392",
    "github": "https://github.com/namratasuryavanshi422-coder"
  },
  {
    "id": 56,
    "name": "Rikhil Gopi",
    "role": "Member (Programming Team)",
    "branch": "CSE",
    "year": 2,
    "email": "rikhilgopi@gmail.com",
    "skills": ["Java", "C++", "Python", "Algorithms", "DSA"],
    "joinDate": "2024-08-15",
    "bio": "I’m Rikhil Sudhir Gopi, a 2nd-year Computer Science student with experience in C++, Java, and Python, along with strong strengths in algorithms and data structures. I’m naturally curious and enjoy understanding how things work, which drives me to explore new areas in technology. I’m currently learning and experimenting with both web development and machine learning as I continue to build and expand my technical abilities.",
    "image": "/images/members/rikhil-gopi.jpg",
    "linkedin": "https://www.linkedin.com/in/rikhil-gopi-a71713312?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "github": "https://github.com/rik0013"
  },
  {
    "id": 57,
    "name": "Suprita Hongal",
    "role": "Member (Programming Team)",
    "branch": "CSAI",
    "year": 2,
    "email": "02fe24bci045@kletech.ac.in",
    "skills": ["C", "C++", "DSA", "Problem-solving", "HTML", "CSS"],
    "joinDate": "2024-08-15",
    "bio": "Name: Suprita Hongal. Department: CSE(AI) Year: 2nd Skills: C, C++, DSA, HTML, CSS. Interests: Problem-solving, coding challenges, building small projects, learning full-stack Coding Club Member: Yes Achievements: – Participated in coding sessions/workshops – Learning DSA & development Goal: To improve my coding skills and work on real projects with the club team.",
    "image": "/images/members/suprita-hongal.jpg",
    "linkedin": "https://www.linkedin.com/in/suprita-hongal-77584933b",
    "github": "https://github.com/SupritaHongal"
  },
  {
    "id": 58,
    "name": "Ankit Raj Sharma",
    "role": "Member (Programming Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "ankit.sharma@kle.edu",
    "skills": ["C++", "Problem Solving"],
    "joinDate": "2024-08-15",
    "bio": "Learning competitive programming",
    "image": "/test-profile.svg"
  },
  {
    "id": 59,
    "name": "Laxmi Nivruti Patil",
    "role": "Member (Programming Team)",
    "branch": "CSE",
    "year": 1,
    "email": "laxminivrutipatil@gmail.com",
    "skills": ["C++"],
    "joinDate": "2024-08-15",
    "bio": "I am a first year cse student. New to programming, but eager to learn new things, and explore technology, and build teamwork and programing skills.",
    "image": "/images/members/laxmi-patil.jpeg",
    "linkedin": "https://www.linkedin.com/in/laxmi-patil-51526a392?utm_source=share_via&utm_content=profile&utm_medium=member_android"
  },
  {
    "id": 69,
    "name": "Siddhi",
    "role": "Member (Programming Team)",
    "branch": "Computer Science",
    "year": 1,
    "email": "siddhi@kle.edu",
    "skills": ["C++", "Problem Solving"],
    "joinDate": "2024-08-15",
    "bio": "Programming enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 60,
    "name": "Shreya S Pai",
    "role": "Member (Programming Team)",
    "branch": "CSAI",
    "year": 2,
    "email": "shreya.pai7@gmail.com",
    "skills": ["C", "C++", "Python", "DSA", "IoT"],
    "joinDate": "2024-08-15",
    "bio": "I’m Shreya S Pai, a 2nd-year CS and AI student who enjoys figuring out how things work in code. I’m building a solid base in programming and problem-solving, especially through DSA and algorithmic thinking. I’ve recently started getting into Java and exploring its concepts to understand structure and logic better. I’m also learning SQL because I like understanding how data is stored and accessed behind the scenes. Outside academics, I love dancing and anything creative that helps me reset.",
    "image": "/images/members/shreya-pai.jpg",
    "linkedin": "https://www.linkedin.com/in/shreya-pai-362b5a342?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    "instagram": "https://www.instagram.com/shreyapaiii?igsh=MWRobGJvNW9nazduZw=="
  },
  {
    "id": 61,
    "name": "Omganesh",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 2,
    "email": "omganesh@kle.edu",
    "skills": ["Graphic Design", "Photoshop", "Illustrator"],
    "joinDate": "2024-08-15",
    "bio": "Graphic design enthusiast",
    "image": "/test-profile.svg"
  },
  {
    "id": 62,
    "name": "Shlok Daga",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 1,
    "email": "shlok.daga@kle.edu",
    "skills": ["UI/UX", "Figma"],
    "joinDate": "2024-08-15",
    "bio": "UI/UX design learner",
    "image": "/test-profile.svg"
  },
  {
    "id": 63,
    "name": "Fatima",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 2,
    "email": "fatima@kle.edu",
    "skills": ["Video Editing", "Design"],
    "joinDate": "2024-08-15",
    "bio": "Video editing specialist",
    "image": "/test-profile.svg"
  },
  {
    "id": 64,
    "name": "Shantkumar",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 1,
    "email": "shantkumar@kle.edu",
    "skills": ["Design", "Creativity"],
    "joinDate": "2024-08-15",
    "bio": "Creative designer",
    "image": "/test-profile.svg"
  },
  {
    "id": 65,
    "name": "Prasanna Hosmani",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 1,
    "email": "prasanna.hosmani@kle.edu",
    "skills": ["Photography", "Editing"],
    "joinDate": "2024-08-15",
    "bio": "Photography and editing enthusiast",
    "image": "/images/members/prasanna-hosmani.heic"
  },
  {
    "id": 66,
    "name": "Aditya Deshpande",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 3,
    "email": "aditya.deshpande@kle.edu",
    "skills": ["Graphic Design", "Video Editing"],
    "joinDate": "2023-08-15",
    "bio": "Creative designer",
    "image": "/test-profile.svg"
  },
  {
    "id": 67,
    "name": "Ayush Shetty",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 3,
    "email": "ayush.shetty@kle.edu",
    "skills": ["UI/UX", "Figma", "Design"],
    "joinDate": "2023-08-15",
    "bio": "UI/UX designer",
    "image": "/test-profile.svg"
  },
  {
    "id": 68,
    "name": "Soumya Honnaik",
    "role": "Member (Media & Design)",
    "branch": "Computer Science",
    "year": 3,
    "email": "soumya.honnaik@kle.edu",
    "skills": ["Graphic Design", "Branding"],
    "joinDate": "2023-08-15",
    "bio": "Brand and graphic designer",
    "image": "/test-profile.svg"
  }
]
"""

# Parse the JSON
members = json.loads(mock_members_data)

# Define the order of IDs
ordered_ids = [
    # Core
    1, 2, 3, 4, 5, 6,
    # Leads
    7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    # Development
    18, 19, 20, 21, 22, 23,
    # AI
    24, 25, 26, 27, 28, 29, 30, 31,
    # Emerging Tech
    32, 33, 34, 35, 36, 37,
    # Competition Management
    38, 39, 40, 41, 42, 43, 44,
    # PR
    45, 46, 47, 48, 49, 50,
    # Programming
    51, 52, 53, 54, 55, 56, 57, 58, 59, 69, 60,
    # Media & Design
    61, 62, 63, 64, 65, 66, 67, 68
]

# Create a map for quick access
member_map = {m['id']: m for m in members}

# Reorder
ordered_members = []
for mid in ordered_ids:
    if mid in member_map:
        member = member_map[mid]
        # Apply name updates
        if mid == 19: member['name'] = 'Shivkumar A Sindolli'
        if mid == 23: member['name'] = 'Abhishek Mannoli'
        if mid == 41: member['name'] = 'Tanusha'
        if mid == 44: member['name'] = 'Sanaha Mugutkhan'
        if mid == 51: member['name'] = 'Lomesh Jangde'
        if mid == 52: member['name'] = 'Arun Mokashi'
        ordered_members.append(member)

# Output the new JS content
print("export const mockMembers = " + json.dumps(ordered_members, indent=2) + ";")
