export const mockEvents = [
    {
        id: 1,
        title: 'Web Dev Bootcamp 2025',
        description: 'A comprehensive bootcamp covering React, Node.js, and modern web development practices. Build real-world projects and get mentored by industry experts.',
        date: '2025-12-15',
        time: '10:00 AM - 4:00 PM',
        location: 'Main Auditorium',
        category: 'Workshop',
        club: 'Development',
        status: 'upcoming',
        attendees: 120,
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['React', 'Node.js', 'Web'],
    },
    {
        id: 2,
        title: 'AI & ML Symposium',
        description: 'Explore the latest trends in Artificial Intelligence and Machine Learning. Featuring guest speakers from top tech companies and hands-on demos.',
        date: '2025-12-20',
        time: '2:00 PM - 6:00 PM',
        location: 'Seminar Hall 1',
        category: 'Seminar',
        club: 'AI',
        status: 'upcoming',
        attendees: 85,
        image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['AI', 'Machine Learning', 'Python'],
    },
    {
        id: 3,
        title: 'HackTheFuture 2025',
        description: 'Our annual flagship hackathon! 24 hours of coding, innovation, and fun. Win prizes worth $5000 and network with potential employers.',
        date: '2026-01-10',
        time: '9:00 AM (24 Hours)',
        location: 'Innovation Hub',
        category: 'Hackathon',
        club: 'Competition',
        status: 'upcoming',
        attendees: 250,
        image: 'https://images.unsplash.com/photo-1504384308090-c54be3855833?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['Hackathon', 'Competition', 'Innovation'],
    },
    {
        id: 4,
        title: 'Intro to Cloud Computing',
        description: 'Learn the basics of AWS and Azure. Understand how to deploy your applications to the cloud and manage infrastructure.',
        date: '2025-11-05',
        time: '11:00 AM - 1:00 PM',
        location: 'Lab 3',
        category: 'Workshop',
        club: 'Emerging Tech',
        status: 'completed',
        attendees: 60,
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['Cloud', 'AWS', 'Azure'],
    },
    {
        id: 5,
        title: 'Competitive Programming 101',
        description: 'Master data structures and algorithms. Prepare for coding interviews and competitive programming contests like ICPC.',
        date: '2025-11-12',
        time: '4:00 PM - 6:00 PM',
        location: 'Lab 2',
        category: 'Workshop',
        club: 'Programming',
        status: 'completed',
        attendees: 90,
        image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['DSA', 'Algorithms', 'C++'],
    },
    {
        id: 6,
        title: 'UI/UX Design Workshop',
        description: 'Learn the principles of user interface and user experience design. Create stunning prototypes using Figma.',
        date: '2025-10-25',
        time: '10:00 AM - 3:00 PM',
        location: 'Design Studio',
        category: 'Workshop',
        club: 'Media & Design',
        status: 'completed',
        attendees: 45,
        image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['Design', 'Figma', 'UI/UX'],
    },
    {
        id: 7,
        title: 'Tech Talk: Future of Blockchain',
        description: 'An insightful session on the applications of blockchain technology beyond cryptocurrencies.',
        date: '2025-10-15',
        time: '3:00 PM - 5:00 PM',
        location: 'Seminar Hall 2',
        category: 'Seminar',
        club: 'Emerging Tech',
        status: 'completed',
        attendees: 70,
        image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['Blockchain', 'Web3', 'Crypto'],
    },
    {
        id: 8,
        title: 'Open Source Contribution Sprint',
        description: 'Get started with open source! We will guide you through making your first pull request to a popular repository.',
        date: '2025-12-28',
        time: '10:00 AM - 6:00 PM',
        location: 'Lab 1',
        category: 'Hackathon',
        club: 'Development',
        status: 'upcoming',
        attendees: 50,
        image: 'https://images.unsplash.com/photo-1607799275518-d58665d099db?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
        tags: ['Open Source', 'Git', 'GitHub'],
    },
];

export const getClubColors = (club) => {
    switch (club) {
        case 'Development': return { gradient: 'from-cyan-500 to-blue-600', text: 'text-cyan-400', border: 'border-cyan-500/30' };
        case 'AI': return { gradient: 'from-purple-500 to-pink-600', text: 'text-purple-400', border: 'border-purple-500/30' };
        case 'Emerging Tech': return { gradient: 'from-green-500 to-teal-600', text: 'text-green-400', border: 'border-green-500/30' };
        case 'Competition': return { gradient: 'from-orange-500 to-red-600', text: 'text-orange-400', border: 'border-orange-500/30' };
        case 'Programming': return { gradient: 'from-indigo-500 to-violet-600', text: 'text-indigo-400', border: 'border-indigo-500/30' };
        case 'Media & Design': return { gradient: 'from-rose-500 to-fuchsia-600', text: 'text-rose-400', border: 'border-rose-500/30' };
        default: return { gradient: 'from-slate-500 to-slate-600', text: 'text-slate-400', border: 'border-slate-500/30' };
    }
};
