/**
 * Mock Members Data
 * ArcStack - KLE Tech Belagavi Campus
 * Academic Cycle 2025 - 2026
 */

export const mockMembers = [
  // Core Committee
  {
    id: 1,
    name: 'Akhilesh Joshi',
    role: 'Chairperson',
    branch: 'Computer Science',
    year: 4,
    email: 'akhilesh.joshi@kle.edu',
    skills: ['Leadership', 'React', 'Node.js', 'Management'],
    joinDate: '2022-08-15',
    bio: 'Leading ArcStack with passion for innovation and technology',
    image: null,
  },
  {
    id: 2,
    name: 'Anushka Singh',
    role: 'Vice Chairperson',
    branch: 'Computer Science',
    year: 3,
    email: 'anushka.singh@kle.edu',
    skills: ['Management', 'Python', 'Web Development'],
    joinDate: '2023-08-15',
    bio: 'Supporting club operations and driving technical excellence',
    image: null,
  },
  {
    id: 3,
    name: 'Pratik Kesarkar',
    role: 'General Secretary',
    branch: 'Computer Science',
    year: 4,
    email: 'pratik.kesarkar@kle.edu',
    skills: ['Organization', 'JavaScript', 'Full Stack'],
    joinDate: '2022-08-15',
    bio: 'Managing club activities and coordinating events',
    image: null,
  },
  {
    id: 4,
    name: 'Shreyas Savant',
    role: 'Deputy General Secretary',
    branch: 'Computer Science',
    year: 3,
    email: 'shreyas.savant@kle.edu',
    skills: ['Coordination', 'React', 'Backend'],
    joinDate: '2023-08-15',
    bio: 'Assisting in club management and technical initiatives',
    image: null,
  },
  {
    id: 5,
    name: 'Samarth Kattimani',
    role: 'Treasurer',
    branch: 'Computer Science',
    year: 4,
    email: 'samarth.kattimani@kle.edu',
    skills: ['Finance', 'Management', 'Web Development'],
    joinDate: '2022-08-15',
    bio: 'Managing club finances and budgeting',
    image: null,
  },
  {
    id: 6,
    name: 'Aniket Patil',
    role: 'Treasurer',
    branch: 'Computer Science',
    year: 3,
    email: 'aniket.patil@kle.edu',
    skills: ['Finance', 'Accounting', 'Python'],
    joinDate: '2023-08-15',
    bio: 'Co-managing financial operations',
    image: null,
  },

  // Functional Team Leads & Co-Leads
  {
    id: 7,
    name: 'Harshit Baliyan',
    role: 'Lead (Development Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'harshit.baliyan@kle.edu',
    skills: ['Full Stack', 'React', 'Node.js', 'MongoDB'],
    joinDate: '2023-08-15',
    bio: 'Leading development team and building scalable applications',
    image: null,
  },
  {
    id: 8,
    name: 'Neil Rego',
    role: 'Lead (AI Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'neil.rego@kle.edu',
    skills: ['Machine Learning', 'Python', 'TensorFlow', 'AI'],
    joinDate: '2023-08-15',
    bio: 'Leading AI initiatives and ML projects',
    image: null,
  },
  {
    id: 9,
    name: 'Rahul Kulkarni',
    role: 'Co-Lead (AI Team)',
    branch: 'Computer Science',
    year: 4,
    email: 'rahul.kulkarni@kle.edu',
    skills: ['Deep Learning', 'Python', 'Data Science'],
    joinDate: '2022-08-15',
    bio: 'Supporting AI team with advanced ML expertise',
    image: null,
  },
  {
    id: 10,
    name: 'Aastha Mishra',
    role: 'Lead (Emerging Tech)',
    branch: 'Computer Science',
    year: 3,
    email: 'aastha.mishra@kle.edu',
    skills: ['Blockchain', 'IoT', 'Cloud Computing'],
    joinDate: '2023-08-15',
    bio: 'Exploring cutting-edge technologies and innovations',
    image: null,
  },
  {
    id: 11,
    name: 'Prakhar Shresh',
    role: 'Co-Lead (Emerging Tech)',
    branch: 'Computer Science',
    year: 3,
    email: 'prakhar.shresh@kle.edu',
    skills: ['AR/VR', 'Web3', 'Cloud'],
    joinDate: '2023-08-15',
    bio: 'Co-leading emerging tech research and development',
    image: null,
  },
  {
    id: 12,
    name: 'Ankit Raj',
    role: 'Lead (Competition Management)',
    branch: 'Computer Science',
    year: 3,
    email: 'ankit.raj@kle.edu',
    skills: ['Competitive Programming', 'Algorithms', 'DSA'],
    joinDate: '2023-08-15',
    bio: 'Managing coding competitions and hackathons',
    image: null,
  },
  {
    id: 13,
    name: 'Bhumika N',
    role: 'Lead (PR Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'bhumika.n@kle.edu',
    skills: ['Public Relations', 'Communication', 'Marketing'],
    joinDate: '2023-08-15',
    bio: 'Managing public relations and outreach',
    image: null,
  },
  {
    id: 14,
    name: 'Aryan Patil',
    role: 'Co-Lead (PR Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'aryan.patil@kle.edu',
    skills: ['Social Media', 'Content Creation', 'Marketing'],
    joinDate: '2024-08-15',
    bio: 'Supporting PR activities and social media management',
    image: null,
  },
  {
    id: 15,
    name: 'Adarsh Kakatkar',
    role: 'Lead (Programming Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'adarsh.kakatkar@kle.edu',
    skills: ['C++', 'Python', 'Algorithms', 'Problem Solving'],
    joinDate: '2023-08-15',
    bio: 'Leading programming team and competitive coding',
    image: null,
  },
  {
    id: 16,
    name: 'Vaibhav Deepa',
    role: 'Co-Lead (Programming Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'vaibhav.deepa@kle.edu',
    skills: ['Java', 'DSA', 'Competitive Programming'],
    joinDate: '2023-08-15',
    bio: 'Co-leading programming initiatives and training',
    image: null,
  },
  {
    id: 17,
    name: 'Anusha Rokhade',
    role: 'Lead (Media & Design)',
    branch: 'Computer Science',
    year: 3,
    email: 'anusha.rokhade@kle.edu',
    skills: ['UI/UX Design', 'Figma', 'Graphic Design', 'Video Editing'],
    joinDate: '2023-08-15',
    bio: 'Leading design team and creating visual content',
    image: null,
  },

  // Development Team Members
  {
    id: 18,
    name: 'Jaydeep Nadkarni',
    role: 'Member (Development Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'jaydeep.nadkarni@kle.edu',
    skills: ['React', 'JavaScript', 'Web Development'],
    joinDate: '2024-08-15',
    bio: 'Building modern web applications',
    image: null,
  },
  {
    id: 19,
    name: 'Shivkumar A Sindolli',
    role: 'Member (Development Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'shivkumar.sindolli@kle.edu',
    skills: ['Node.js', 'Backend', 'APIs'],
    joinDate: '2024-08-15',
    bio: 'Backend development enthusiast',
    image: null,
  },
  {
    id: 20,
    name: 'Samiksha',
    role: 'Member (Development Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'samiksha@kle.edu',
    skills: ['Frontend', 'CSS', 'JavaScript'],
    joinDate: '2024-08-15',
    bio: 'Creating beautiful user interfaces',
    image: null,
  },
  {
    id: 21,
    name: 'Kartik Hirenarti',
    role: 'Member (Development Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'kartik.hirenarti@kle.edu',
    skills: ['HTML', 'CSS', 'JavaScript'],
    joinDate: '2024-08-15',
    bio: 'Learning web development',
    image: null,
  },
  {
    id: 22,
    name: 'Divya Gour',
    role: 'Member (Development Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'divya.gour@kle.edu',
    skills: ['React', 'Frontend'],
    joinDate: '2024-08-15',
    bio: 'Frontend development learner',
    image: null,
  },
  {
    id: 23,
    name: 'Abhishek Mamoli',
    role: 'Member (Development Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'abhishek.mamoli@kle.edu',
    skills: ['JavaScript', 'Web Development'],
    joinDate: '2024-08-15',
    bio: 'Aspiring full stack developer',
    image: null,
  },

  // AI Team Members
  {
    id: 24,
    name: 'Harshit Jakati',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'harshit.jakati@kle.edu',
    skills: ['Machine Learning', 'Python', 'TensorFlow'],
    joinDate: '2023-08-15',
    bio: 'AI and ML enthusiast',
    image: null,
  },
  {
    id: 25,
    name: 'Chandrakanth D U',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'chandrakanth.du@kle.edu',
    skills: ['Deep Learning', 'Python', 'Neural Networks'],
    joinDate: '2024-08-15',
    bio: 'Exploring deep learning',
    image: null,
  },
  {
    id: 26,
    name: 'Arpita Malalikar',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'arpita.malalikar@kle.edu',
    skills: ['Machine Learning', 'Data Science', 'Python'],
    joinDate: '2024-08-15',
    bio: 'Data science and ML practitioner',
    image: null,
  },
  {
    id: 27,
    name: 'Vaishnavi Modekar',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'vaishnavi.modekar@kle.edu',
    skills: ['AI', 'Python', 'Machine Learning'],
    joinDate: '2024-08-15',
    bio: 'AI research enthusiast',
    image: null,
  },
  {
    id: 28,
    name: 'Chinmayi T',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'chinmayi.t@kle.edu',
    skills: ['Python', 'Machine Learning'],
    joinDate: '2024-08-15',
    bio: 'Learning AI and ML',
    image: null,
  },
  {
    id: 29,
    name: 'Shreya Kalaj',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'shreya.kalaj@kle.edu',
    skills: ['Python', 'Data Analysis'],
    joinDate: '2024-08-15',
    bio: 'Data analysis and AI learner',
    image: null,
  },
  {
    id: 30,
    name: 'Varshini Kulkarni',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'varshini.kulkarni@kle.edu',
    skills: ['Python', 'Machine Learning'],
    joinDate: '2024-08-15',
    bio: 'Aspiring ML engineer',
    image: null,
  },
  {
    id: 31,
    name: 'Varsha B',
    role: 'Member (AI Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'varsha.b@kle.edu',
    skills: ['Python', 'AI'],
    joinDate: '2024-08-15',
    bio: 'AI enthusiast',
    image: null,
  },

  // Emerging Tech Members
  {
    id: 32,
    name: 'Manmohan Havanur',
    role: 'Member (Emerging Tech)',
    branch: 'Computer Science',
    year: 1,
    email: 'manmohan.havanur@kle.edu',
    skills: ['Blockchain', 'Web3'],
    joinDate: '2024-08-15',
    bio: 'Blockchain technology explorer',
    image: null,
  },
  {
    id: 33,
    name: 'Rudra Kulkarni',
    role: 'Member (Emerging Tech)',
    branch: 'Computer Science',
    year: 1,
    email: 'rudra.kulkarni@kle.edu',
    skills: ['IoT', 'Cloud Computing'],
    joinDate: '2024-08-15',
    bio: 'IoT and cloud enthusiast',
    image: null,
  },
  {
    id: 34,
    name: 'Siddu Patil',
    role: 'Member (Emerging Tech)',
    branch: 'Computer Science',
    year: 1,
    email: 'siddu.patil@kle.edu',
    skills: ['AR/VR', 'Emerging Tech'],
    joinDate: '2024-08-15',
    bio: 'Exploring AR/VR technologies',
    image: null,
  },
  {
    id: 35,
    name: 'Shivaleela',
    role: 'Member (Emerging Tech)',
    branch: 'Computer Science',
    year: 2,
    email: 'shivaleela@kle.edu',
    skills: ['Cloud', 'DevOps'],
    joinDate: '2024-08-15',
    bio: 'Cloud computing learner',
    image: null,
  },
  {
    id: 36,
    name: 'Namrata',
    role: 'Member (Emerging Tech)',
    branch: 'Computer Science',
    year: 1,
    email: 'namrata@kle.edu',
    skills: ['Blockchain', 'Web3'],
    joinDate: '2024-08-15',
    bio: 'Web3 technology enthusiast',
    image: null,
  },
  {
    id: 37,
    name: 'Aditya',
    role: 'Member (Emerging Tech)',
    branch: 'Computer Science',
    year: 1,
    email: 'aditya@kle.edu',
    skills: ['IoT', 'Emerging Tech'],
    joinDate: '2024-08-15',
    bio: 'Emerging technologies explorer',
    image: null,
  },

  // Competition Management Members
  {
    id: 38,
    name: 'Daivik Naik',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 3,
    email: 'daivik.naik@kle.edu',
    skills: ['Competitive Programming', 'Algorithms', 'DSA'],
    joinDate: '2023-08-15',
    bio: 'Competitive programming expert',
    image: null,
  },
  {
    id: 39,
    name: 'Srushti Payannawar',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 1,
    email: 'srushti.payannawar@kle.edu',
    skills: ['Problem Solving', 'Algorithms'],
    joinDate: '2024-08-15',
    bio: 'Problem solving enthusiast',
    image: null,
  },
  {
    id: 40,
    name: 'Sumedha Upadhye',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 1,
    email: 'sumedha.upadhye@kle.edu',
    skills: ['Competitive Programming', 'DSA'],
    joinDate: '2024-08-15',
    bio: 'Learning competitive programming',
    image: null,
  },
  {
    id: 41,
    name: 'Tanisha',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 3,
    email: 'tanisha@kle.edu',
    skills: ['Algorithms', 'Problem Solving'],
    joinDate: '2023-08-15',
    bio: 'Algorithm design enthusiast',
    image: null,
  },
  {
    id: 42,
    name: 'Vaibhav',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 1,
    email: 'vaibhav@kle.edu',
    skills: ['DSA', 'Competitive Programming'],
    joinDate: '2024-08-15',
    bio: 'DSA learner',
    image: null,
  },
  {
    id: 43,
    name: 'Shreya Pai',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 2,
    email: 'shreya.pai@kle.edu',
    skills: ['Problem Solving', 'Algorithms'],
    joinDate: '2024-08-15',
    bio: 'Competitive coding enthusiast',
    image: null,
  },
  {
    id: 44,
    name: 'Sanaha Mugurkhan',
    role: 'Member (Competition Management)',
    branch: 'Computer Science',
    year: 1,
    email: 'sanaha.mugurkhan@kle.edu',
    skills: ['Algorithms', 'DSA'],
    joinDate: '2024-08-15',
    bio: 'Algorithm enthusiast',
    image: null,
  },

  // PR Team Members
  {
    id: 45,
    name: 'Pavitra H',
    role: 'Member (PR Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'pavitra.h@kle.edu',
    skills: ['Communication', 'Social Media', 'Marketing'],
    joinDate: '2024-08-15',
    bio: 'Social media and PR specialist',
    image: null,
  },
  {
    id: 46,
    name: 'Sneha Hundekar',
    role: 'Member (PR Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'sneha.hundekar@kle.edu',
    skills: ['Public Relations', 'Content Creation'],
    joinDate: '2024-08-15',
    bio: 'Content creator and PR enthusiast',
    image: null,
  },
  {
    id: 47,
    name: 'Saumya Shaikh',
    role: 'Member (PR Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'saumya.shaikh@kle.edu',
    skills: ['Communication', 'Marketing'],
    joinDate: '2024-08-15',
    bio: 'Marketing and communication learner',
    image: null,
  },
  {
    id: 48,
    name: 'Mallikarjungouda Patil',
    role: 'Member (PR Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'mallikarjungouda.patil@kle.edu',
    skills: ['Public Relations', 'Social Media'],
    joinDate: '2024-08-15',
    bio: 'PR and social media enthusiast',
    image: null,
  },
  {
    id: 49,
    name: 'Pranjali Muragakar',
    role: 'Member (PR Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'pranjali.muragakar@kle.edu',
    skills: ['Marketing', 'Communication'],
    joinDate: '2023-08-15',
    bio: 'Marketing specialist',
    image: null,
  },
  {
    id: 50,
    name: 'Spandana B',
    role: 'Member (PR Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'spandana.b@kle.edu',
    skills: ['Content Creation', 'Social Media'],
    joinDate: '2024-08-15',
    bio: 'Content and social media specialist',
    image: null,
  },

  // Programming Team Members
  {
    id: 51,
    name: 'Lomesh Jangde',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'lomesh.jangde@kle.edu',
    skills: ['C++', 'Python', 'Algorithms'],
    joinDate: '2023-08-15',
    bio: 'Competitive programmer',
    image: null,
  },
  {
    id: 52,
    name: 'Arun Mokashi',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'arun.mokashi@kle.edu',
    skills: ['Java', 'DSA', 'Problem Solving'],
    joinDate: '2023-08-15',
    bio: 'DSA and problem solving expert',
    image: null,
  },
  {
    id: 53,
    name: 'Samarth Narvekar',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 3,
    email: 'samarth.narvekar@kle.edu',
    skills: ['C++', 'Algorithms', 'Competitive Programming'],
    joinDate: '2023-08-15',
    bio: 'Algorithm design specialist',
    image: null,
  },
  {
    id: 54,
    name: 'Darshan Kittur',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'darshan.kittur@kle.edu',
    skills: ['Python', 'DSA'],
    joinDate: '2024-08-15',
    bio: 'DSA enthusiast',
    image: null,
  },
  {
    id: 55,
    name: 'Namrata S',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'namrata.s@kle.edu',
    skills: ['C++', 'Problem Solving'],
    joinDate: '2024-08-15',
    bio: 'Problem solving learner',
    image: null,
  },
  {
    id: 56,
    name: 'Rikhil Gopi',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'rikhil.gopi@kle.edu',
    skills: ['Java', 'Algorithms'],
    joinDate: '2024-08-15',
    bio: 'Algorithm enthusiast',
    image: null,
  },
  {
    id: 57,
    name: 'Suprita Hongal',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 2,
    email: 'suprita.hongal@kle.edu',
    skills: ['Python', 'DSA'],
    joinDate: '2024-08-15',
    bio: 'Competitive programming learner',
    image: null,
  },
  {
    id: 58,
    name: 'Ankit Raj Sharma',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'ankit.sharma@kle.edu',
    skills: ['C++', 'Problem Solving'],
    joinDate: '2024-08-15',
    bio: 'Learning competitive programming',
    image: null,
  },
  {
    id: 59,
    name: 'Laxmi Patil',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'laxmi.patil@kle.edu',
    skills: ['Python', 'Algorithms'],
    joinDate: '2024-08-15',
    bio: 'Algorithm learner',
    image: null,
  },
  {
    id: 60,
    name: 'Siddhi',
    role: 'Member (Programming Team)',
    branch: 'Computer Science',
    year: 1,
    email: 'siddhi@kle.edu',
    skills: ['C++', 'DSA'],
    joinDate: '2024-08-15',
    bio: 'DSA learner',
    image: null,
  },

  // Media & Design Members
  {
    id: 61,
    name: 'Omganesh',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 2,
    email: 'omganesh@kle.edu',
    skills: ['Graphic Design', 'Photoshop', 'Illustrator'],
    joinDate: '2024-08-15',
    bio: 'Graphic design enthusiast',
    image: null,
  },
  {
    id: 62,
    name: 'Shlok Daga',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 1,
    email: 'shlok.daga@kle.edu',
    skills: ['UI/UX', 'Figma'],
    joinDate: '2024-08-15',
    bio: 'UI/UX design learner',
    image: null,
  },
  {
    id: 63,
    name: 'Fatima',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 2,
    email: 'fatima@kle.edu',
    skills: ['Video Editing', 'Design'],
    joinDate: '2024-08-15',
    bio: 'Video editing specialist',
    image: null,
  },
  {
    id: 64,
    name: 'Shantkumar',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 1,
    email: 'shantkumar@kle.edu',
    skills: ['Graphic Design', 'Canva'],
    joinDate: '2024-08-15',
    bio: 'Design enthusiast',
    image: null,
  },
  {
    id: 65,
    name: 'Prasanna Hosmani',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 1,
    email: 'prasanna.hosmani@kle.edu',
    skills: ['UI/UX', 'Design'],
    joinDate: '2024-08-15',
    bio: 'UI/UX learner',
    image: null,
  },
  {
    id: 66,
    name: 'Aditya Deshpande',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 3,
    email: 'aditya.deshpande@kle.edu',
    skills: ['Graphic Design', 'Video Editing'],
    joinDate: '2023-08-15',
    bio: 'Creative designer',
    image: null,
  },
  {
    id: 67,
    name: 'Ayush Shetty',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 3,
    email: 'ayush.shetty@kle.edu',
    skills: ['UI/UX', 'Figma', 'Design'],
    joinDate: '2023-08-15',
    bio: 'UI/UX designer',
    image: null,
  },
  {
    id: 68,
    name: 'Soumya Honnaik',
    role: 'Member (Media & Design)',
    branch: 'Computer Science',
    year: 3,
    email: 'soumya.honnaik@kle.edu',
    skills: ['Graphic Design', 'Branding'],
    joinDate: '2023-08-15',
    bio: 'Brand and graphic designer',
    image: null,
  },
];


/**
 * Get all unique roles
 * @returns {Array} Array of unique roles
 */
export function getAllRoles() {
  const roles = mockMembers.map((member) => member.role);
  return [...new Set(roles)].sort();
}

/**
 * Get all unique branches
 * @returns {Array} Array of unique branches
 */
export function getAllBranches() {
  const branches = mockMembers.map((member) => member.branch);
  return [...new Set(branches)].sort();
}

/**
 * Get all unique years
 * @returns {Array} Array of unique years
 */
export function getAllYears() {
  const years = mockMembers.map((member) => member.year);
  return [...new Set(years)].sort((a, b) => a - b);
}

/**
 * Get member by ID
 * @param {number} id - Member ID
 * @returns {Object} Member object or null
 */
export function getMemberById(id) {
  return mockMembers.find((member) => member.id === id) || null;
}

/**
 * Filter members by criteria
 * @param {Object} filters - Filter criteria
 * @returns {Array} Filtered members
 */
export function filterMembers(filters) {
  return mockMembers.filter((member) => {
    if (filters.role && member.role !== filters.role) return false;
    if (filters.branch && member.branch !== filters.branch) return false;
    if (filters.year && member.year !== parseInt(filters.year)) return false;
    if (filters.search) {
      const searchLower = filters.search.toLowerCase();
      return (
        member.name.toLowerCase().includes(searchLower) ||
        member.role.toLowerCase().includes(searchLower) ||
        member.branch.toLowerCase().includes(searchLower) ||
        member.skills.some((skill) => skill.toLowerCase().includes(searchLower))
      );
    }
    return true;
  });
}
